#!/bin/bash
green=$(tput setaf 2)
yellow=$(tput setaf 3)
red=$(tput setaf 1)
reset=$(tput sgr0)

COMMIT_RANGE=$(echo $TRAVIS_COMMIT_RANGE | sed 's/\.\.\./\.\./g')
COMMIT_MESSAGES=$(echo $(git log $COMMIT_RANGE --pretty=format:%s))

DEPLOY_SCRIPT=$1

shopt -s nocasematch
#####################################################################################
########## CHECKS TO SEE IF BUILD IS TRIGGERED FROM PULL REQUEST ####################
##########  IF IT IS NOT IT CHECKS BRANCH TO BUILD SPECIFIC APK  ####################
#####################################################################################
if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [[ "$TRAVIS_BRANCH" == "travis" ]]; then
    echo "${green}*** BUILDING DEVELOPMENT PAYMENTS APK ***${reset}"
    ../../IntegratedPayments/gradlew :carecloudmini:assembleDevelopment --profile --configure-on-demand

    echo "${green}*** DELETING DEVELOPMENT APKS FROM AWS ***${reset}"
    AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY aws s3 rm s3://automation-zeus --recursive --exclude "*" --include "*carecloudmini*development*.apk"

    echo "${green}*** DEPLOYING DEVELOPMENT PAYMENTS APK TO AWS ***${reset}"
    mkdir $TRAVIS_BUILD_DIR/IntegratedPayments/carecloudmini/build/outputs/temp/
    find $TRAVIS_BUILD_DIR/IntegratedPayments/carecloudmini/build/outputs/apk/ -name "*development*.apk" -exec cp {}  $TRAVIS_BUILD_DIR/IntegratedPayments/carecloudmini/build/outputs/temp/ \;

    PAYMENTS_APP=$(echo $TRAVIS_BUILD_DIR/IntegratedPayments/carecloudmini/build/outputs/temp/$(ls $TRAVIS_BUILD_DIR/IntegratedPayments/carecloudmini/build/outputs/temp/ | grep -i '.*carecloudmini.*release.*\.apk') )

    AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY aws s3 cp $TRAVIS_BUILD_DIR/IntegratedPayments/carecloudmini/build/outputs/temp s3://automation-zeus/ --recursive

    echo "${green}*** BUILDING DEVELOPMENT PRACTICE APK ***${reset}"
    ./gradlew :CarePayPracticeTablet:assembleDevelopment --profile --configure-on-demand

    echo "${green}*** DELETING DEVELOPMENT APKS FROM AWS ***${reset}"
    AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY aws s3 rm s3://automation-zeus --recursive --exclude "*" --include "*CarePayPracticeTablet*development*.apk"

    echo "${green}*** DEPLOYING DEVELOPMENT PRACTICE APK TO AWS ***${reset}"
    mkdir $TRAVIS_BUILD_DIR/CarePay/CarePayPracticeTablet/build/outputs/temp/
    find $TRAVIS_BUILD_DIR/CarePay/CarePayPracticeTablet/build/outputs/apk/ -name "*development*.apk" -exec cp {}  $TRAVIS_BUILD_DIR/CarePay/CarePayPracticeTablet/build/outputs/temp/ \;

    PRACTICE_APP=$(echo $TRAVIS_BUILD_DIR/CarePay/CarePayPracticeTablet/build/outputs/temp/$(ls $TRAVIS_BUILD_DIR/CarePay/CarePayPracticeTablet/build/outputs/temp/ | grep -i '.*practice.*release.*\.apk') )

    AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY aws s3 cp $TRAVIS_BUILD_DIR/CarePay/CarePayPracticeTablet/build/outputs/temp s3://automation-zeus/ --recursive

    echo "${green}*** BUILDING DEVELOPMENT PATIENT APK ***${reset}"
    ./gradlew :CarePayPatient:assembleDevelopment --profile --configure-on-demand

    echo "${green}*** DELETING DEVELOPMENT APKS FROM AWS ***${reset}"
    AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY aws s3 rm s3://automation-zeus --recursive --exclude "*" --include "*CarePayPatient*development*.apk"

    echo "${green}*** DEPLOYING DEVELOPMENT PATIENT APK TO AWS ***${reset}"
    mkdir $TRAVIS_BUILD_DIR/CarePay/CarePayPatient/build/outputs/temp/
    find $TRAVIS_BUILD_DIR/CarePay/CarePayPatient/build/outputs/apk/ -name "*development*.apk" -exec cp {}  $TRAVIS_BUILD_DIR/CarePay/CarePayPatient/build/outputs/temp/ \;

    PATIENT_APP=$(echo $TRAVIS_BUILD_DIR/CarePay/CarePayPatient/build/outputs/temp/$(ls $TRAVIS_BUILD_DIR/CarePay/CarePayPatient/build/outputs/temp/ | grep -i '.*patient.*release.*\.apk') )

    AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY aws s3 cp $TRAVIS_BUILD_DIR/CarePay/CarePayPatient/build/outputs/temp s3://automation-zeus/ --recursive

elif [ "$TRAVIS_PULL_REQUEST" == "false" ] && [[ "$TRAVIS_BRANCH" == "QA" ]]; then

    echo "${green}*** BUILDING QA PRACTICE APK ***${reset}"
    ./gradlew :CarePayPracticeTablet:assembleQa --profile --configure-on-demand

    echo "${green}*** DELETING DEVELOPMENT APKS FROM AWS ***${reset}"
    AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY aws s3 rm s3://automation-zeus --recursive --exclude "*" --include "*CarePayPracticeTablet*qa*.apk"

    echo "${green}*** DEPLOYING QA PRACTICE APK TO AWS ***${reset}"
    mkdir $TRAVIS_BUILD_DIR/CarePay/CarePayPracticeTablet/build/outputs/temp/
    find $TRAVIS_BUILD_DIR/CarePay/CarePayPracticeTablet/build/outputs/apk/ -name "*qa*.apk" -exec cp {}  $TRAVIS_BUILD_DIR/CarePay/CarePayPracticeTablet/build/outputs/temp/ \;

    AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY aws s3 cp $TRAVIS_BUILD_DIR/CarePay/CarePayPracticeTablet/build/outputs/temp s3://automation-zeus/ --recursive

    echo "${green}*** BUILDING QA PATIENT APK ***${reset}"
    ./gradlew :CarePayPatient:assembleQa --profile --configure-on-demand

    echo "${green}*** DELETING DEVELOPMENT APKS FROM AWS ***${reset}"
    AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY aws s3 rm s3://automation-zeus --recursive --exclude "*" --include "*CarePayPatient*qa*.apk"

    echo "${green}*** DEPLOYING QA PATIENT APK TO AWS ***${reset}"
    mkdir $TRAVIS_BUILD_DIR/CarePay/CarePayPatient/build/outputs/temp/
    find $TRAVIS_BUILD_DIR/CarePay/CarePayPatient/build/outputs/apk/ -name "*qa*.apk" -exec cp {}  $TRAVIS_BUILD_DIR/CarePay/CarePayPatient/build/outputs/temp/ \;

    AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY aws s3 cp $TRAVIS_BUILD_DIR/CarePay/CarePayPatient/build/outputs/temp s3://automation-zeus/ --recursive

elif [ "$TRAVIS_PULL_REQUEST" == "false" ] && [[ "$TRAVIS_BRANCH" == "Staging" ]]; then

    echo "${green}*** BUILDING STAGING PRACTICE APK ***${reset}"
    ./gradlew :CarePayPracticeTablet:assembleStaging --profile --configure-on-demand

    echo "${green}*** DELETING DEVELOPMENT APKS FROM AWS ***${reset}"
    AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY aws s3 rm s3://automation-zeus --recursive --exclude "*" --include "*CarePayPracticeTablet*staging*.apk"

    echo "${green}*** DEPLOYING STAGING PRACTICE APKS TO AWS ***${reset}"
    mkdir $TRAVIS_BUILD_DIR/CarePay/CarePayPracticeTablet/build/outputs/temp/
    find $TRAVIS_BUILD_DIR/CarePay/CarePayPracticeTablet/build/outputs/apk/ -name "*staging*.apk" -exec cp {}  $TRAVIS_BUILD_DIR/CarePay/CarePayPracticeTablet/build/outputs/temp/ \;

    AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY aws s3 cp $TRAVIS_BUILD_DIR/CarePay/CarePayPracticeTablet/build/outputs/temp s3://automation-zeus/ --recursive

    echo "${green}*** BUILDING STAGING PATIENT APK ***${reset}"
    ./gradlew :CarePayPatient:assembleStaging --profile --configure-on-demand

    echo "${green}*** DELETING DEVELOPMENT APKS FROM AWS ***${reset}"
    AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY aws s3 rm s3://automation-zeus --recursive --exclude "*" --include "*CarePayPatient*staging*.apk"

    echo "${green}*** DEPLOYING STAGING PATIENT APKS TO AWS ***${reset}"
    mkdir $TRAVIS_BUILD_DIR/CarePay/CarePayPatient/build/outputs/temp/
    find $TRAVIS_BUILD_DIR/CarePay/CarePayPatient/build/outputs/apk/ -name "*staging*.apk" -exec cp {}  $TRAVIS_BUILD_DIR/CarePay/CarePayPatient/build/outputs/temp/ \;

    AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY aws s3 cp $TRAVIS_BUILD_DIR/CarePay/CarePayPatient/build/outputs/temp s3://automation-zeus/ --recursive

elif [ "$TRAVIS_PULL_REQUEST" == "false" ] && [[ "$TRAVIS_BRANCH" == "master" ]]; then

    echo "${green}*** BUILDING PRODUCTION PRACTICE APK ***${reset}"
    ./gradlew :CarePayPracticeTablet:assembleProduction --profile --configure-on-demand

    echo "${green}*** DELETING DEVELOPMENT APKS FROM AWS ***${reset}"
    AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY aws s3 rm s3://automation-zeus --recursive --exclude "*" --include "*CarePayPracticeTablet*production*.apk"

    echo "${green}*** DEPLOYING PRODUCTION PRACTICE APK TO AWS ***${reset}"
    mkdir $TRAVIS_BUILD_DIR/CarePay/CarePayPracticeTablet/build/outputs/temp/
    find $TRAVIS_BUILD_DIR/CarePay/CarePayPracticeTablet/build/outputs/apk/ -name "*production*.apk" -exec cp {}  $TRAVIS_BUILD_DIR/CarePay/CarePayPracticeTablet/build/outputs/temp/ \;

    AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY aws s3 cp $TRAVIS_BUILD_DIR/CarePay/CarePayPracticeTablet/build/outputs/temp s3://automation-zeus/ --recursive

    echo "${green}*** BUILDING PRODUCTION PATIENT APK ***${reset}"
    ./gradlew :CarePayPatient:assembleProduction --profile --configure-on-demand

    echo "${green}*** DELETING DEVELOPMENT APKS FROM AWS ***${reset}"
    AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY aws s3 rm s3://automation-zeus --recursive --exclude "*" --include "*CarePayPatient*production*.apk"

    echo "${green}*** DEPLOYING PRODUCTION PATIENT APK TO AWS ***${reset}"
    mkdir $TRAVIS_BUILD_DIR/CarePay/CarePayPatient/build/outputs/temp/
    find $TRAVIS_BUILD_DIR/CarePay/CarePayPatient/build/outputs/apk/ -name "*production*.apk" -exec cp {}  $TRAVIS_BUILD_DIR/CarePay/CarePayPatient/build/outputs/temp/ \;

    AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY aws s3 cp $TRAVIS_BUILD_DIR/CarePay/CarePayPatient/build/outputs/temp s3://automation-zeus/ --recursive

fi

#####################################################################################
##########              CHECKS COMMIT MESSAGE FOR VERSION OF APP             ########
##########  EXAMPLE "PRACTICEAPP" OR "PATIENTAPP" AND COMPILES THAT PROJECT  ########
#####################################################################################
if [ "$TRAVIS_PULL_REQUEST" != "false" ] && [[ "$COMMIT_MESSAGES" =~ clover.*app ]]; then
    echo "${yellow}*** Skipping APK Build ***${reset}"
    echo "${green}*** Clover App Compile Check ***${reset}"
    ./gradlew :CarePayPracticeClover:compileProductionReleaseSources --profile --configure-on-demand
    echo "${green}*** Patient App Compile Check ***${reset}"
    ./gradlew :CarePayPatient:compileProductionReleaseSources --profile --configure-on-demand
    echo "${green}*** Practice App Compile Check ***${reset}"
    ./gradlew :CarePayPracticeTablet:compileProductionReleaseSources --profile --configure-on-demand
elif [ "$TRAVIS_PULL_REQUEST" != "false" ] && [[ "$COMMIT_MESSAGES" =~ carepay ]]; then
    echo "${yellow}*** Skipping APK Build ***${reset}"
    echo "${yellow}*** Skipping Compile Check ***${reset}"
elif [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
    echo "${yellow}*** Skipping APK Build ***${reset}"
    echo "${green}*** Practice App Compile Check ***${reset}"
    ./gradlew :CarePayPracticeTablet:compileProductionReleaseSources --profile --configure-on-demand
    echo "${green}*** Patient App Compile Check ***${reset}"
    ./gradlew :CarePayPatient:compileProductionReleaseSources --profile --configure-on-demand
fi


########### TEST FAIRY DEPLOY ###########
if [[ $DEPLOY_SCRIPT == "testfairy" ]]; then
    echo "${green}*** Deploying via TestFairy ***${reset}"

    if [[ $PATIENT_APP ]]; then
        echo "${green}*** Deploy Patient App Build ***${reset}"
        chmod +x ./$DEPLOY_SCRIPT
        ./$DEPLOY_SCRIPT $PATIENT_APP
    else
        echo
        echo "${red}*** No Patient App Build to Deploy ***${reset}"
    fi

    if [[ $PRACTICE_APP ]]; then
        echo "${green}*** Deploy Practice App Build ***${reset}"
        chmod +x ./$DEPLOY_SCRIPT
        ./$DEPLOY_SCRIPT $PRACTICE_APP
    else
        echo
        echo "${red}*** No Practice App Build to Deploy ***${reset}"
    fi
fi
#########################################
